// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "proto/user.proto" (package "user", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { UserService } from "./user";
import type { CreateUserRequest } from "./user";
import type { UserResponse } from "./user";
import type { UserRequest } from "./user";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { AuthResponse } from "./user";
import type { GoogleLoginRequest } from "./user";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service user.UserService
 */
export interface IUserServiceClient {
    /**
     * @generated from protobuf rpc: LoginWithGoogle
     */
    loginWithGoogle(input: GoogleLoginRequest, options?: RpcOptions): UnaryCall<GoogleLoginRequest, AuthResponse>;
    /**
     * @generated from protobuf rpc: GetUser
     */
    getUser(input: UserRequest, options?: RpcOptions): UnaryCall<UserRequest, UserResponse>;
    /**
     * @generated from protobuf rpc: CreateUser
     */
    createUser(input: CreateUserRequest, options?: RpcOptions): UnaryCall<CreateUserRequest, UserResponse>;
}
/**
 * @generated from protobuf service user.UserService
 */
export class UserServiceClient implements IUserServiceClient, ServiceInfo {
    typeName = UserService.typeName;
    methods = UserService.methods;
    options = UserService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: LoginWithGoogle
     */
    loginWithGoogle(input: GoogleLoginRequest, options?: RpcOptions): UnaryCall<GoogleLoginRequest, AuthResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GoogleLoginRequest, AuthResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetUser
     */
    getUser(input: UserRequest, options?: RpcOptions): UnaryCall<UserRequest, UserResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<UserRequest, UserResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreateUser
     */
    createUser(input: CreateUserRequest, options?: RpcOptions): UnaryCall<CreateUserRequest, UserResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateUserRequest, UserResponse>("unary", this._transport, method, opt, input);
    }
}
